name: Renovate Bot
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 4 * * *"
  pull_request:
    paths:
      - .github/renovate.json
      - .github/workflows/renovate-bot.yaml

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.17
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
